"""RAG ingestion 与检索领域。"""

from jarvis_worker.agent.rag.contracts import (
    EmbeddingProvider,
    OcrProvider,
    OcrResult,
    OcrSpan,
    RagAsset,
    RagAssetFileStore,
    RagAssetKind,
    RagChunk,
    RagChunkElementLink,
    RagChunkElementRelation,
    RagDocument,
    RagDocumentStatus,
    RagElement,
    RagElementType,
    RagExtractionMethod,
    RagIngestionJob,
    RagIngestionStatus,
    RagSearchMatch,
    RagVectorRecord,
    VectorIndex,
    VisualDescription,
    VisualDescriptionProvider,
)
from jarvis_worker.agent.rag.identifiers import (
    build_element_locator_key,
    deterministic_asset_id,
    deterministic_chunk_element_link_id,
    deterministic_element_id,
)

__all__ = [
    "EmbeddingProvider",
    "OcrProvider",
    "OcrResult",
    "OcrSpan",
    "RagAsset",
    "RagAssetFileStore",
    "RagAssetKind",
    "RagChunk",
    "RagChunkElementLink",
    "RagChunkElementRelation",
    "RagDocument",
    "RagDocumentStatus",
    "RagElement",
    "RagElementType",
    "RagExtractionMethod",
    "RagIngestionJob",
    "RagIngestionStatus",
    "RagSearchMatch",
    "RagVectorRecord",
    "VectorIndex",
    "VisualDescription",
    "VisualDescriptionProvider",
    "build_element_locator_key",
    "deterministic_asset_id",
    "deterministic_chunk_element_link_id",
    "deterministic_element_id",
]
