from datetime import datetime
from typing import Protocol
from uuid import UUID

from jarvis_worker.shared.domain.models import KnowledgeDocument, KnowledgeVault


class KnowledgeVaultRepository(Protocol):
    async def insert_if_absent(self, vault: KnowledgeVault) -> bool: ...
    async def get(self, vault_id: UUID) -> KnowledgeVault | None: ...
    async def get_by_canonical_path(self, path: str) -> KnowledgeVault | None: ...
    async def list_active(self) -> list[KnowledgeVault]: ...
    async def activate_exclusive(self, vault_id: UUID, at: datetime) -> None: ...


class KnowledgeDocumentRepository(Protocol):
    async def create(self, document: KnowledgeDocument) -> KnowledgeDocument: ...
    async def list_by_vault(self, vault_id: UUID, limit: int = 100) -> list[KnowledgeDocument]: ...
