# Alembic configuration

[alembic]
# 迁移脚本目录
script_location = src/jarvis_worker/migrations

# sqlalchemy.url 优先从 JARVIS_DATABASE_URL 环境变量读取
sqlalchemy.url = postgresql+asyncpg://jarvis:jarvis@127.0.0.1:5432/jarvis

# 日志
file_template = %%(year)d-%%(month).2d-%%(day).2d_%%(hour).2d-%%(minute).2d-%%(second).2d_%%(slug)s

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
