<script setup lang="ts">
import type { RuntimeDeadLetterSummaryDTO, RuntimeStreamHealthDTO } from "@jarvis/shared";
const props = defineProps<{ streams: RuntimeStreamHealthDTO[]; deadLetters: RuntimeDeadLetterSummaryDTO[] }>();
const labels: Record<string, string> = { run_queue: "Run Queue", worker_command: "Worker Command", runtime_event: "Runtime Event" };
function dlqCount(name: string) { return props.deadLetters.find((item) => item.name === name)?.count ?? 0; }
function formatDuration(ms: number) { if (ms <= 0) return "—"; if (ms < 1000) return `${ms} ms`; return `${Math.round(ms / 1000)} s`; }
</script>
<template>
  <section class="overflow-hidden rounded-lg border border-[var(--color-border)] bg-white"><div class="border-b border-[var(--color-border)] px-4 py-3"><h2 class="text-sm font-medium text-[var(--color-text)]">消息链路</h2><p class="mt-1 text-xs text-[var(--color-muted)]">来自 Redis consumer group 的实时治理元数据，不读取消息内容。</p></div><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-xs"><thead class="bg-gray-50 text-[var(--color-muted)]"><tr><th class="px-4 py-2.5 font-medium">链路</th><th class="px-3 py-2.5 font-medium">状态</th><th class="px-3 py-2.5 font-medium">Lag</th><th class="px-3 py-2.5 font-medium">Pending</th><th class="px-3 py-2.5 font-medium">最老 Pending</th><th class="px-3 py-2.5 font-medium">Consumers</th><th class="px-3 py-2.5 font-medium">DLQ</th></tr></thead><tbody class="divide-y divide-[var(--color-border)]"><tr v-for="stream in streams" :key="stream.name"><td class="px-4 py-3"><div class="font-medium text-[var(--color-text)]">{{ labels[stream.name] }}</div><div class="mt-0.5 font-mono text-[10px] text-[var(--color-muted)]">{{ stream.consumer_group }}</div></td><td class="px-3 py-3"><span class="rounded-full px-2 py-1" :class="stream.available ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-600'">{{ stream.available ? "可用" : (stream.error_code || "不可用") }}</span></td><td class="px-3 py-3 tabular-nums">{{ stream.lag < 0 ? "—" : stream.lag }}</td><td class="px-3 py-3 tabular-nums">{{ stream.pending }}</td><td class="px-3 py-3 tabular-nums">{{ formatDuration(stream.oldest_pending_ms) }}</td><td class="px-3 py-3 tabular-nums">{{ stream.consumers }}</td><td class="px-3 py-3 tabular-nums">{{ dlqCount(stream.name) }}</td></tr></tbody></table></div></section>
</template>
